### ISSUE TITLE
Dataset

### ISSUE THREAD

**Issue by killamorri07** [Adriana172/Snoring-Detection#1]
Hello, I have been working on a similar project. I don't know how to reach out to you thus I post in this segment. 
Is the dataset used in this project is also open sources? 

Thank you

**Comment by adrianagaler** [comment]
Hello Killa,

Yes. The dataset is open source. You can find it on Kaggle
https://www.kaggle.com/datasets/tareqkhanemu/snoring . However, I augmented
it since it is a small one.

**Comment by thelou1s** [comment]
So I need download and rename to Snoring_Dataset/0? Thank you
FileNotFoundError: [Errno 2] No such file or directory: './Snoring_Dataset/0'
