### ISSUE TITLE
Snore detection operating procedure

### ISSUE THREAD

**Issue by DanieChan** [Adriana172/Snoring-Detection#3]
Good day,

Was wondering that after deployment procedures to obtain snore detection. Is the procedure to run the training(train_snoring_model) and then the the snore detection file(test_snoring_model.ipynb)?
Thanks in advance!

**Comment by yaojiayu0826** [comment]
> Good day,
> 
> Was wondering that after deployment procedures to obtain snore detection. Is the procedure to run the training(train_snoring_model) and then the the snore detection file(test_snoring_model.ipynb)? Thanks in advance!

Yes, train_snoring_model trains the model and deploy the model to the microcontroller (see steps in that notebook). test_snoring_model.ipynb evaluates model performance on the hold out dataset
